[metadata]
title = "Newsletter del Lunes."
no = 18
date = "25 Noviembre 2024"
welcome = """
<br><br>
"""
[[articles]]
number = 1
url = ""
type = "TEXT"
cat = "GENERAL"
summary = "."

[[articles]]
number = 2
url = ""
type = "TEXT"
cat = "GENERAL"
summary = "."

[[articles]]
number = 3
url = ""
type = "TEXT"
cat = "GENERAL"
summary = "."

[[articles]]
number = 4
url = ""
type = "TEXT"
cat = "GENERAL"
summary = "."
