[metadata]
title = "Newsletter del Lunes."
no = 25
date = "31 Marzo 2025"
welcome = """
Buenas a todos,
</br></br>
</br></br>
Poco mas, ya me contaréis. Un saludo!
"""

[[articles]]
number = 1
url = ""
type = "TEXT"
cat = "GENERAL"
summary = "."

[[articles]]
number = 2
url = ""
type = "TEXT"
cat = "GENERAL"
summary = "."

[[articles]]
number = 3
url = ""
type = "TEXT"
cat = "GENERAL"
summary = "."

[[articles]]
number = 4
url = ""
type = "TEXT"
cat = "GENERAL"
summary = "."
