[metadata]
title = "ix Friday Fill-Ins"
no = 21
date = "18 Jan 2019"
welcome = """

"""

[[articles]]
url = "https://vimeo.com/36579366"
type = "VIDEO"
cat = "GENERAL"
summary = ""

[[articles]]
url = "http://www.technovelgy.com/ct/content.asp?Bnum=1024"
type = "TEXT"
cat = "GENERAL"
summary = "A vision for e-books from almost 60 years ago!"

[[articles]]
url = "http://norvig.com/21-days.html"
type = "TEXT"
cat = "DEV"
summary = ""

[[articles]]
url = "http://blogs.dropbox.com/tech/2019/01/courier-dropbox-migration-to-grpc/"
type = "TEXT"
cat = "DEV"
summary = ""

[[articles]]
url = "https://scottbot.net/the-route-of-a-text-message/"
type = "TEXT"
cat = "GENERAL"
summary = ""

[[articles]]
url = "https://www.youtube.com/watch?v=p0jGmgIrf_M"
type = "VIDEO"
cat = "DEV"
summary = ""

[[articles]]
url = "https://www.justonecookbook.com/ginger-rice/"
type = "TEXT"
cat = "RECIPE"
summary = ""